### ISSUE TITLE
1 failing spec in Debian ia64

### ISSUE THREAD

**Issue by terceiro** [ffi/ffi#157]
```
Failures:

  1) Callback returning struct by value
     Failure/Error: Unable to find matching line from backtrace
       expected: 18
            got: 0 (using ==)
     # ./spec/ffi/callback_spec.rb:254
```

That spec is the following:

```
  it "returning struct by value" do
    s = LibTest::S8F32S32.new
    s[:s8] = 0x12
    s[:s32] = 0x1eefbeef
    s[:f32] = 1.234567
    ret = LibTest.testCallbackVrT { s }
    ret[:s8].should == s[:s8]
    ret[:f32].should == s[:f32]
    ret[:s32].should == s[:s32]

  end
```

The failing expectation is the first one, `ret[:s8].should == s[:s8]`, but I guess the others would fail as well.

Is there any information I can get on the platform to help fixing this?
