### ISSUE TITLE
Test failures with ffi 1.9.0

### ISSUE THREAD

**Issue by graaff** [ffi/ffi#273]
With ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux] I'm seeing the following two test failures on Gentoo Linux:

```
  1) variable-length arrays zero length array should be accepted as last field
     Failure/Error: lambda {
       expected no Exception, got #<TypeError: type of field 1 has zero size> with backtrace:
         # ./lib/ffi/struct_layout_builder.rb:155:in `initialize'
         # ./lib/ffi/struct_layout_builder.rb:155:in `new'
         # ./lib/ffi/struct_layout_builder.rb:155:in `build'
         # ./lib/ffi/struct.rb:264:in `layout'
         # ./spec/ffi/struct_spec.rb:714:in `block (4 levels) in <top (required)>'
         # ./spec/ffi/struct_spec.rb:713:in `initialize'
         # ./spec/ffi/struct_spec.rb:713:in `new'
         # ./spec/ffi/struct_spec.rb:713:in `block (3 levels) in <top (required)>'
         # ./spec/ffi/struct_spec.rb:712:in `block (2 levels) in <top (required)>'
     # ./spec/ffi/struct_spec.rb:712:in `block (2 levels) in <top (required)>'

  2) variable-length arrays can access elements of array
     Failure/Error: layout :count, :int, :data, [ :long, 0 ]
     TypeError:
       type of field 1 has zero size
     # ./lib/ffi/struct_layout_builder.rb:155:in `initialize'
     # ./lib/ffi/struct_layout_builder.rb:155:in `new'
     # ./lib/ffi/struct_layout_builder.rb:155:in `build'
     # ./lib/ffi/struct.rb:264:in `layout'
     # ./spec/ffi/struct_spec.rb:729:in `block (3 levels) in <top (required)>'
     # ./spec/ffi/struct_spec.rb:728:in `initialize'
     # ./spec/ffi/struct_spec.rb:728:in `new'
     # ./spec/ffi/struct_spec.rb:728:in `block (2 levels) in <top (required)>'
```

Please let me know if you need more information to further diagnose this.
